import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translations = language === 'en' ? enTranslations : zhTranslations;
    const keys = key.split('.');
    let value: any = translations;
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// English translations
const enTranslations = {
  header: {
    home: 'Home',
    partners: 'Partners',
    solutions: 'Solutions',
    about: 'About',
    products: 'Products',
    caseStudies: 'Case Studies',
    contact: 'Contact',
    login: 'Login',
    getStarted: 'Get Started',
    loading: 'Loading...',
    noPartners: 'No partners available',
    iotConnectivity: 'IoT Connectivity',
    m2mPlatform: 'M2M Platform',
    deviceManagement: 'Device Management',
    analytics: 'Analytics & Insights',
    customSolutions: 'Custom Solutions',
  },
  hero: {
    companyName: 'ISL - Inclusive Information Services Limited',
    title1: 'Global IoT & M2M Connectivity,',
    title2: 'Engineered Locally',
    description: 'Powering millions of IoT devices across China, India, EU, USA, and Singapore with carrier-grade reliability',
    iotSolutions: 'IoT Solutions',
    m2mConnectivity: 'M2M Connectivity',
    support: '24/7 Support',
    scrollDown: 'Scroll Down',
  },
  about: {
    title: 'Global IoT & M2M Connectivity, Engineered Locally',
    subtitle1: 'We bridge the gap between global reach and local expertise, delivering seamless IoT connectivity across continents.',
    subtitle2: 'Trusted by enterprises worldwide, ISL powers millions of connected devices with carrier-grade reliability and regional compliance.',
    globalOperations: 'Global Operations',
    active: 'Active',
    ourValues: 'Our Values',
    compliance: 'Compliance',
    value1: 'Reliability: 99.9% uptime SLA backed by redundant networks',
    value2: 'Local Expertise: In-country regulatory compliance and support',
    value3: 'Innovation: Cutting-edge IoT solutions for evolving needs',
    value4: 'Transparency: Clear pricing with no hidden fees',
    miit: 'MIIT',
    miitDesc: 'China Ministry Approved',
    trai: 'TRAI',
    traiDesc: 'India Telecom Authority',
    ce: 'CE',
    ceDesc: 'European Conformity',
    fcc: 'FCC',
    fccDesc: 'USA Federal Certified',
    ctaTitle: 'Ready to Connect Globally?',
    ctaDesc: 'Book a 15-minute discovery call to discuss your IoT connectivity needs',
    bookCall: 'Book Discovery Call',
    china1: 'China',
    chinaLocation: 'Shanghai',
    china2: 'China',
    HKLocation: 'Hong Kong',
    india: 'India',
    indiaLocation: 'Mumbai & Delhi',
    eu: 'EU',
    euLocation: 'Stockholm',
    usa: 'USA',
    usaLocation: 'Chicago',
  },
  cta: {
    title: "Let's Connect Your IoT Ecosystem",
    description: 'Start your global IoT deployment with ISL. Contact us for a personalized consultation.',
    namePlaceholder: 'Your Name',
    emailPlaceholder: 'Email Address',
    companyPlaceholder: 'Company Name',
    submitButton: 'Request a Consultation',
    reachUs: 'Or reach us directly at:',
    contactInfo: 'INCLUSIVE-SALES@inclusive.com.cn',
  },
  solutions: {
    title: 'Enterprise IoT Solutions',
    subtitle: 'End-to-end connectivity solutions tailored for your IoT deployment needs',
    globalIotSim: 'Global IoT SIM',
    globalIotSimDesc: 'eUICC-enabled SIMs for seamless global roaming across 180+ countries',
    globalIotSimBenefit: 'One SIM, worldwide connectivity',
    privateApn: 'Private APN + VPN + InterCloud',
    privateApnDesc: 'Dedicated network tunnels with enterprise-grade security for sensitive IoT data',
    privateApnBenefit: 'Bank-level security for your devices',
    smsVoice: 'SMS & Voice for IoT',
    smsVoiceDesc: 'Two-way SMS and voice channels for device management and critical alerts',
    smsVoiceBenefit: 'Real-time device communication',
    chinaApproval: 'China Type-Approval & Whitelist',
    chinaApprovalDesc: 'Full MIIT certification and network whitelist service for China market entry',
    chinaApprovalBenefit: 'Fast-track China market access',
    indiaDlt: 'India DLT Onboarding',
    indiaDltDesc: 'Complete DLT registration bundle for TRAI-compliant promotional SMS campaigns',
    indiaDltBenefit: 'Launch SMS campaigns in 48 hours',
    learnMore: 'Learn More',
    detailTitle: 'Solution Details',
    keyFeatures: 'Key Features',
    technicalSpecs: 'Technical Specifications',
    useCases: 'Use Cases',
    globalIotSimDetail: {
      overview: 'Our Global IoT SIM solution provides seamless connectivity across 180+ countries with automatic network switching, ensuring your devices stay connected wherever they are deployed.',
      feature1: 'eUICC Technology - Remote SIM provisioning and over-the-air profile management',
      feature2: 'Multi-IMSI Support - Automatic carrier switching for optimal coverage and cost',
      feature3: 'Global Coverage - Access to 600+ carrier networks worldwide',
      feature4: 'Flexible Data Plans - Pay-as-you-go or pooled data options',
      spec1: 'Form Factors: 2FF, 3FF, 4FF, MFF2, and eSIM',
      spec2: 'Network Types: 2G, 3G, 4G LTE, 5G NR',
      spec3: 'Temperature Range: -40°C to +105°C (industrial grade)',
      spec4: 'Lifespan: 10+ years operational life',
      useCase1: 'Connected vehicles and fleet management',
      useCase2: 'Asset tracking and logistics',
      useCase3: 'Smart agriculture and environmental monitoring',
    },
    privateApnDetail: {
      overview: 'Enterprise-grade security solution providing isolated network tunnels for your IoT devices with military-grade encryption and direct cloud integration.',
      feature1: 'Private APN - Dedicated network path separate from public internet',
      feature2: 'VPN Tunneling - End-to-end encrypted data transmission',
      feature3: 'InterCloud Connect - Direct integration with AWS, Azure, and GCP',
      feature4: 'Static IP Allocation - Fixed IP addresses for enterprise firewall rules',
      spec1: 'Encryption: AES-256 for data in transit',
      spec2: 'Authentication: Mutual TLS and certificate-based',
      spec3: 'Latency: <50ms to cloud endpoints',
      spec4: 'Throughput: Up to 10Gbps dedicated bandwidth',
      useCase1: 'Financial services and payment terminals',
      useCase2: 'Healthcare devices with PHI data',
      useCase3: 'Critical infrastructure and SCADA systems',
    },
    smsVoiceDetail: {
      overview: 'Reliable two-way SMS and voice communication channels designed specifically for IoT device management, alerts, and remote diagnostics.',
      feature1: 'MT/MO SMS - Both mobile-terminated and mobile-originated messaging',
      feature2: 'Voice Calls - Inbound and outbound voice for diagnostics',
      feature3: 'Delivery Reports - Real-time message delivery confirmation',
      feature4: 'Global Routing - Optimized SMS routing for 99.9% delivery',
      spec1: 'SMS Throughput: 200+ messages per second',
      spec2: 'Delivery Time: Average <5 seconds globally',
      spec3: 'Message Length: Up to 1600 characters (concatenated)',
      spec4: 'Voice Quality: HD voice where network supports',
      useCase1: 'Remote device configuration and updates',
      useCase2: 'Critical alert notifications and alarms',
      useCase3: 'Two-factor authentication for IoT devices',
    },
  },
  products: {
    title: 'Flexible Pricing Plans',
    subtitle: 'Choose the plan that fits your IoT deployment scale',
    prepaid: 'Pre-paid',
    postpaid: 'Post-paid',
    popular: 'Popular',
    getStarted: 'Get Started',
    customSolution: 'Need a custom solution?',
    contactSales: 'Contact our sales team',
    starterPack: 'Starter SIM Pack',
    volumePlans: 'Volume Plans',
    oemWhiteLabel: 'OEM White-Label SIM',
    managementPortal: 'Management Portal',
    perSim3Months: 'per SIM / 3 months',
    basedOnVolume: 'based on volume',
    perSimMoq: 'per SIM (10K+ MOQ)',
    withAllPlans: 'with all plans',
    included: 'Included',
    custom: 'Custom',
  },
  footer: {
    companyDesc: 'Leading provider of IoT M2M connectivity solutions for businesses worldwide.',
    services: 'Services',
    iotConnectivity: 'IoT Connectivity',
    m2mSolutions: 'M2M Solutions',
    networkSecurity: 'Network Security',
    dataManagement: 'Data Management',
    company: 'Company',
    aboutUs: 'About Us',
    careers: 'Careers',
    partners: 'Partners',
    contact: 'Contact',
    contactUs: 'Contact Us',
    whatsappSupport: 'WhatsApp Support',
    chinaOffice: 'China Office',
    chinaLocation: 'Shanghai, China',
    indiaOffice: 'India Office',
    indiaLocation: 'Mumbai & Delhi, India',
    euOffice: 'EU Office',
    euLocation: 'Amsterdam, Netherlands',
    copyright: '© 2025 Inclusive Information Services Limited. All rights reserved.',
  },
  caseStudy: {
    title: 'Customer Success Stories',
    subtitle: 'See how leading companies trust ISL for their global IoT deployments',
    backToHome: 'Back to Home',
    theChallenge: 'The Challenge',
    ourSolution: 'Our Solution',
    results: 'Results',
    contactUs: 'Contact Us',
    readMore: 'Read Story',
    slogan: 'Trusted by Industry Leaders',
    ev: {
      badge: 'Automotive',
      title: 'EV Telematics Success Story',
      shortTitle: "EV Telematics",
      subtitle: 'Real-time vehicle diagnostics and fleet management globally',
      metric1: 'Active SIMs',
      metric2: 'Countries',
      metric3: 'Uptime',
      metric4: '180 Countries',
      highlight: '99% uptime',
      challengeText1: 'A leading electric vehicle manufacturer needed a reliable, scalable IoT connectivity solution to support their rapidly global expansion. Their existing connectivity infrastructure was fragmented across multiple carriers, leading to coverage gaps, inconsistent performance, and complex billing.',
      challengeText2: 'The company required real-time vehicle diagnostics, over-the-air updates, and fleet management capabilities across 100+ countries, with seamless roaming and carrier-grade reliability.',
      solution1Title: 'Global Multi-Service-Provider-Supported SIM Cards',
      solution1Desc: 'Deployed eUICC-enabled SIM cards with multiple service providers supports, enabling automatic network switching for optimal coverage and cost efficiency across all operating regions.',
      solution2Title: 'Private APN & VPN Security',
      solution2Desc: 'Implemented enterprise-grade security with dedicated private APN and VPN tunnels to protect sensitive vehicle data and ensure secure over-the-air updates.',
      solution3Title: 'Real-Time Management Portal',
      solution3Desc: 'Provided comprehensive connectivity management platform with real-time diagnostics, usage analytics, and automated alerting for proactive issue resolution.',
      result1: '99% uptime across all markets, exceeding SLA requirements',
      result2: '40% reduction in connectivity costs through optimized carrier selection',
      result3: 'Seamless expansion of vehicles sales across continents without infrastructure changes',
      result4: 'Real-time diagnostics enabling predictive maintenance and reduced downtime',
      ctaTitle: 'Ready to Scale Your IoT Fleet?',
      ctaDesc: "Let's discuss how ISL can power your connected vehicle solution",
    },
    smartMeter: {
      badge: 'Energy',
      title: 'Smart Meter OEM Success Story',
      shortTitle: "Smart Meter OEM",
      subtitle: 'Low-power metering solution with extended device lifecycle',
      metric1: 'Low-data SIMs',
      metric2: 'Battery Life',
      metric3: 'Cost Reduction',
      metric4: '800K Low-data SIMs • 10-year battery',
      highlight: '50% cost reduction',
      challengeText1: 'A smart meter manufacturer needed an ultra-low-power connectivity solution that could support 10+ year battery life for remote utility metering deployments. Traditional cellular connectivity was too power-hungry and costly for large-scale meter deployments.',
      challengeText2: 'The solution required deep indoor penetration, minimal power consumption, and cost-effective data plans for infrequent, small data transmissions typical of utility metering applications.',
      solution1Title: 'Low-data Connectivity',
      solution1Desc: 'Deployed specialized Low-data SIM cards optimized for ultra-low power consumption, enabling 10+ year battery life with superior indoor coverage and penetration.',
      solution2Title: 'Optimized Data Plans',
      solution2Desc: 'Implemented cost-effective data plans tailored for infrequent, small-packet transmissions typical of smart meter communications, reducing operational costs by 50%.',
      solution3Title: 'Automated Provisioning',
      solution3Desc: 'Streamlined SIM activation and device onboarding through automated provisioning APIs, reducing deployment time and eliminating manual configuration errors.',
      result1: 'Tens of thousands meters deployed with 10+ year battery life achieved',
      result2: '50% cost reduction compared to previous connectivity solution',
      result3: '99% read success rate even in challenging indoor environments',
      result4: 'Zero-touch deployment through automated provisioning APIs',
      ctaTitle: 'Need Low-Power IoT Connectivity?',
      ctaDesc: 'Discover how low-data cards can power your utility or smart city deployment',
    },
    GPS: {
      badge: 'Global Supply-Chain Visibility',
      title: 'GPS & Multi-Modal Tracking Success Story',
      shortTitle: "GPS Tracking",
      subtitle: 'One Belt, One Road, One View',
      metric2: 'Countries Crossed',
      metric3: 'Platform Uptime',
      metric4: 'The New Silk Route',
      highlight: '100% compliance',
      challengeText1: 'A leading electric vehicle manufacturer needed a reliable, scalable IoT connectivity solution to support their rapidly expanding fleet across Europe and Asia. Their existing connectivity infrastructure was fragmented across multiple carriers, leading to coverage gaps, inconsistent performance, and complex billing.',
      challengeText2: "The company required real-time vehicle tracking, diagnostics, over-the-air updates, and fleet management capabilities across 62 countries, with seamless roaming and carrier-grade reliability.",
      solution1Title: 'Global Top50 MNO Service Provider',
      solution1Desc: 'Deployed single SIM card, enabling automatic network switching for optimal coverage and cost efficiency across all operating regions under OBOR, the New Silk Route.',
      solution2Title: 'Factory-Friendly Logistics',
      solution2Desc: 'Single SIM works for domestic China testing, OBOR rail, European after-sales.',
      solution3Title: 'Real-Time Management Portal',
      solution3Desc: 'Provided comprehensive connectivity management platform with real-time diagnostics, usage analytics, and automated alerting for proactive issue resolution.',
      result1: '99% uptime across all markets, exceeding SLA requirements',
      result2: '40% reduction in connectivity costs through optimized carrier selection',
      result3: 'Chinese OEM turned a 35-day sea voyage into an 18-day rail sprint without adding single extra SIM',
      result4: 'Real-time diagnostics enabling predictive maintenance and reduced downtime',
      ctaTitle: 'One Belt, One Road, One View',
      ctaDesc: "Let's discuss GPS Tracking IoT solutions for your Business Case",
    },
    medical: {
      badge: 'Healthcare',
      title: 'Medical Device Success Story',
      shortTitle: "Medical Device",
      subtitle: 'FDA & MIIT certified connectivity for global medical IoT deployment',
      metric1: 'FDA Approved',
      metric2: 'MIIT Certified',
      metric3: 'Dual Market',
      challengeText1: 'A medical device manufacturer needed to launch their connected patient monitoring system in both US and China markets simultaneously. The challenge involved navigating complex regulatory requirements while maintaining secure, HIPAA-compliant data transmission.',
      challengeText2: 'Different certification processes, network requirements, and data privacy regulations in each market created significant deployment complexity and risk of delays.',
      solution1Title: 'Regulatory Compliance Package',
      solution1Desc: 'Provided end-to-end support for FDA certification in US and MIIT type-approval in China, including technical documentation, network compliance proof, and certification guidance.',
      solution2Title: 'HIPAA-Compliant Connectivity',
      solution2Desc: 'Implemented private APN with encrypted connections meeting HIPAA requirements for Protected Health Information (PHI), ensuring patient data security across both markets.',
      solution3Title: 'Dual-Market SIM Solution',
      solution3Desc: 'Deployed unified eUICC SIM cards certified for both markets, eliminating the need for separate inventory and simplifying supply chain management.',
      result1: 'FDA approval and MIIT certification achieved within 6 months',
      result2: 'Simultaneous launch in US and China markets',
      result3: '100% HIPAA compliance with zero data breach incidents',
      result4: '30% faster time-to-market compared to competitors',
      ctaTitle: 'Ready to Launch Your Medical IoT Device?',
      ctaDesc: "Let's navigate regulatory compliance together for your healthcare IoT deployment",
    },
    mobility: {
      badge: 'Transportation',
      title: 'Shared Mobility Platform Success Story',
      shortTitle: "Shared Mobility",
      subtitle: 'DLT-compliant SMS campaigns driving user engagement in India',
      metric1: 'Messages/Month',
      metric2: 'DLT Compliance',
      metric3: 'Open Rate',
      challengeText1: 'A major shared mobility platform struggled with SMS campaign delivery in India due to complex DLT (Distributed Ledger Technology) regulations introduced by TRAI. Their promotional messages were being blocked, causing significant drops in user engagement and booking rates.',
      challengeText2: 'The platform needed rapid DLT registration, template approval, and sender ID whitelisting across multiple telecom operators to restore their marketing capabilities.',
      solution1Title: 'Complete DLT Onboarding',
      solution1Desc: 'Handled end-to-end DLT registration process including entity onboarding, template creation and approval, sender ID registration, and operator whitelisting.',
      solution2Title: 'Template Optimization',
      solution2Desc: 'Optimized SMS templates for maximum approval rates while maintaining marketing effectiveness, creating pre-approved template library for quick campaign deployment.',
      solution3Title: 'Multi-Operator Integration',
      solution3Desc: 'Integrated with all major Indian telecom operators ensuring consistent delivery rates and comprehensive coverage across the entire user base.',
      result1: '5M+ compliant SMS messages delivered monthly',
      result2: '100% DLT compliance with zero message blocking',
      result3: '40% improvement in SMS open rates',
      result4: '48-hour DLT setup for new campaign templates',
      ctaTitle: 'Need DLT-Compliant SMS in India?',
      ctaDesc: "Let's get your promotional campaigns running at full capacity",
    },
  },
};

// Chinese Simplified translations
const zhTranslations = {
  header: {
    home: '首页',
    partners: '合作伙伴',
    solutions: '解决方案',
    about: '关于我们',
    products: '产品服务',
    caseStudies: '成功案例',
    contact: '联系我们',
    login: '登录',
    getStarted: '立即开始',
    loading: '加载中...',
    noPartners: '暂无合作伙伴',
    iotConnectivity: '物联网连接',
    m2mPlatform: 'm2m平台',
    deviceManagement: '设备管理',
    analytics: '数据分析与洞察',
    customSolutions: '定制化解决方案',
  },
  hero: {
    companyName: 'ISL - 并蓄信息技术服务有限公司',
    title1: '全球化物联网与m2m连接服务，',
    title2: '本地化专业部署',
    description: '为中国、印度、欧盟、美国及新加坡等地数百万台物联网设备提供运营商级可靠连接',
    iotSolutions: '物联网解决方案',
    m2mConnectivity: 'm2m连接',
    support: '7×24小时支持',
    scrollDown: '向下滚动',
  },
  about: {
    title: '全球化物联网与m2m连接服务，本地化专业部署',
    subtitle1: '我们搭建全球覆盖与本地专长之间的桥梁，提供跨大洲的无缝物联网连接服务。',
    subtitle2: '作为全球企业信赖的合作伙伴，ISL以运营商级可靠性和区域合规性，为数百万台联网设备提供网络服务支持。',
    globalOperations: '全球业务布局',
    active: '运营中',
    ourValues: '我们的价值观',
    compliance: '合规认证',
    value1: '可靠性：99.9% 运行时间服务等级协议，依托冗余网络保障',
    value2: '本地专长：提供境内监管合规支持与本地化服务',
    value3: '创新性：为不断变化的需求提供前沿物联网解决方案',
    value4: '透明度：定价清晰，无隐藏费用',
    miit: '工信部',
    miitDesc: '中国工信部认证',
    trai: '印度电信管理局',
    traiDesc: '印度电信管理局合规',
    ce: '欧盟CE认证',
    ceDesc: '欧盟符合性认证',
    fcc: '美国联邦通信委员会',
    fccDesc: '美国联邦通信委员会认证',
    ctaTitle: '准备好开启全球连接之旅？',
    ctaDesc: '预约15分钟的通话，讨论您的物联网连接需求',
    bookCall: '预约通话',
    china1: '中国',
    chinaLocation: '上海',
    china2: '中国',
    HKLocation: '香港',
    india: '印度',
    indiaLocation: '孟买 & 德里',
    eu: '欧盟',
    euLocation: '斯德哥尔摩',
    usa: '美国',
    usaLocation: '芝加哥',
  },
  cta: {
    title: '让我们助力您的物联网生态系统互联',
    description: '与ISL携手，开启您的全球物联网部署之旅。联系我们获取个性化咨询服务。',
    namePlaceholder: '您的姓名',
    emailPlaceholder: '电子邮箱',
    companyPlaceholder: '公司名称',
    submitButton: '申请咨询',
    reachUs: '或直接联系我们：',
    contactInfo: 'INCLUSIVE-SALES@inclusive.com.cn',
  },
  solutions: {
    title: '企业级物联网解决方案',
    subtitle: '为您的物联网部署需求量身打造端到端连接解决方案',
    globalIotSim: '全球物联网SIM卡',
    globalIotSimDesc: '支持eUICC的SIM卡，可在180多个国家实现无缝全球漫游',
    globalIotSimBenefit: '一张SIM卡，全球畅联',
    privateApn: '私有APN + VPN + 跨云互联',
    privateApnDesc: '专用网络隧道，具备企业级安全性，保障敏感物联网数据传输',
    privateApnBenefit: '为您的设备提供银行级安全防护',
    smsVoice: '物联网短信与语音服务',
    smsVoiceDesc: '双向短信与语音通道，支持设备管理与紧急警报通知',
    smsVoiceBenefit: '设备实时通信',
    chinaApproval: '中国型号核准与白名单',
    chinaApprovalDesc: '提供完整工信部认证与网络白名单服务，助力开拓中国市场',
    chinaApprovalBenefit: '快速进入中国市场',
    indiaDlt: '印度DLT平台入驻',
    indiaDltDesc: '完整DLT注册服务包，支持符合印度电信管理局要求的营销短信活动',
    indiaDltBenefit: '48小时内启动短信营销活动',
    learnMore: '了解更多',
    detailTitle: '解决方案详情',
    keyFeatures: '核心功能',
    technicalSpecs: '技术规格',
    useCases: '应用场景',
    globalIotSimDetail: {
      overview: '我们的全球物联网SIM卡解决方案可在180多个国家提供无缝连接服务，支持自动网络切换，确保您的设备无论部署在何处都能保持稳定连接。',
      feature1: 'eUICC技术 - 远程SIM卡配置与空中配置文件管理',
      feature2: '多IMSI支持 - 自动运营商切换，实现最优覆盖与成本',
      feature3: '全球覆盖 - 接入全球600多个运营商网络',
      feature4: '灵活数据套餐 - 按需付费或流量池共享选项',
      spec1: '物理规格：2FF、3FF、4FF、MFF2及eSIM',
      spec2: '网络制式：2G、3G、4G LTE、5G NR',
      spec3: '工作温度：-40°C至+105°C（工业级）',
      spec4: '使用寿命：10年以上运行寿命',
      useCase1: '联网车辆与车队管理',
      useCase2: '资产追踪与物流',
      useCase3: '智慧农业与环境监测',
    },
    privateApnDetail: {
      overview: '企业级安全解决方案，为您的物联网设备提供隔离网络隧道，采用军用级加密并支持直接云集成。',
      feature1: '私有APN - 独立于公共互联网的专用网络路径',
      feature2: 'VPN隧道 - 端到端加密数据传输',
      feature3: '跨云互联 - 直接集成AWS、Azure和GCP',
      feature4: '静态IP分配 - 为企业防火墙规则提供固定IP地址',
      spec1: '加密方式：传输中数据采用AES-256加密',
      spec2: '身份验证：双向TLS和基于证书的认证',
      spec3: '延迟：到云端点<50ms',
      spec4: '吞吐量：高达10Gbps专用带宽',
      useCase1: '金融服务与支付终端',
      useCase2: '涉及受保护健康信息（PHI）的医疗设备',
      useCase3: '关键基础设施与SCADA系统',
    },
    smsVoiceDetail: {
      overview: '专为物联网设备管理、警报通知和远程诊断设计的可靠双向短信与语音通信通道。',
      feature1: 'MT/MO短信 - 同时支持移动终端接收和移动终端发起的消息',
      feature2: '语音通话 - 支持诊断的入站与出站语音',
      feature3: '送达报告 - 实时消息送达确认',
      feature4: '全球路由 - 优化短信路由，送达率达99.9%',
      spec1: '短信吞吐量：每秒200条以上消息',
      spec2: '送达时间：全球平均<5秒',
      spec3: '消息长度：最多1600字符（拼接消息）',
      spec4: '语音质量：网络支持时提供高清语音',
      useCase1: '远程设备配置与更新',
      useCase2: '紧急警报通知与告警',
      useCase3: '物联网设备双因素身份验证',
    },
  },
  products: {
     title: '灵活定价方案',
     subtitle: '根据您的物联网部署规模选择合适方案',
     prepaid: '预付费',
     postpaid: '后付费',
     popular: '热门推荐',
     getStarted: '立即办理',
     customSolution: '需要定制化解决方案？',
     contactSales: '联系销售团队',
     starterPack: '入门级SIM卡套餐',
     volumePlans: '大容量套餐',
     oemWhiteLabel: 'OEM白标SIM卡',
     managementPortal: '管理平台',
     perSim3Months: '每张SIM卡 / 3个月',
     basedOnVolume: '按用量计费',
     perSimMoq: '每张SIM卡（最低起订量1万张）',
     withAllPlans: '所有方案均包含',
     included: '已包含',
     custom: '定制化',
  },
  footer: {
      companyDesc: '全球领先的企业级物联网与m2m连接解决方案提供商。',
      services: '服务项目',
      iotConnectivity: '物联网连接',
      m2mSolutions: 'm2m解决方案',
      networkSecurity: '网络安全',
      dataManagement: '数据管理',
      company: '公司信息',
      aboutUs: '关于我们',
      careers: '招贤纳士',
      partners: '合作伙伴',
      contact: '联系我们',
      contactUs: '联系我们',
      chinaOffice: '中国办公室',
      chinaLocation: '中国上海',
      indiaOffice: '印度办公室',
      indiaLocation: '印度孟买 & 德里',
      euOffice: '欧盟办公室',
      euLocation: '荷兰阿姆斯特丹',
      copyright: '© 2025 并蓄信息技术服务有限公司 保留所有权利。',
  },
  caseStudy: {
    title: '客户成功案例',
    subtitle: '了解领先企业如何信赖ISL的全球物联网部署服务',
    backToHome: '返回首页',
    theChallenge: '面临挑战',
    ourSolution: '我们的解决方案',
    results: '实施成果',
    contactUs: '联系我们',
    readMore: '阅读详情',
    slogan: '与以下行业领军企业合作',
    ev: {
      badge: '汽车行业',
      title: '电动汽车远程信息处理成功案例',
      shortTitle: "电动汽车远程信息处理",
      subtitle: '全球范围内的实时车辆诊断与车队管理',
      metric1: '在用SIM卡数量',
      metric2: '覆盖国家',
      metric3: '运行时间',
      metric4: '180个国家',
      highlight: '99%运行时间',
      challengeText1: '某领先电动汽车制造商需要可靠、可扩展的物联网连接解决方案，以支持其快速的全球扩张。其现有连接基础设施分散在多个运营商之间，导致覆盖缺口、性能不一致和计费复杂等问题。',
      challengeText2: '该公司需要在100多个国家提供实时车辆诊断、远程在线更新和车队管理功能，并要求具备无缝漫游能力和运营商级可靠性。',
      solution1Title: '支持全球多服务提供商的SIM卡',
      solution1Desc: '部署支持多漫游商的eUICC SIM卡，可在所有运营区域自动切换网络，实现最优覆盖与成本效益。',
      solution2Title: '私有APN与VPN安全防护',
      solution2Desc: '通过专用私有APN和VPN隧道构建企业级安全体系，保护敏感车辆数据并确保远程在线更新的安全性。',
      solution3Title: '实时管理平台',
      solution3Desc: '提供全面的连接管理平台，具备实时诊断、用量分析和自动告警功能，支持主动问题解决。',
      result1: '所有市场均实现99%运行时间，超出服务等级协议要求',
      result2: '通过优化运营商选择，连接成本降低40%',
      result3: '无需更改基础设施，即可实现车辆销售的跨大洲无缝扩张',
      result4: '实时诊断功能支持预测性维护，减少停机时间',
      ctaTitle: '准备好扩展您的物联网车队？',
      ctaDesc: '让我们探讨ISL如何为您的联网车辆解决方案提供支持',
    },
    smartMeter: {
      badge: '能源行业',
      title: '智能电表原始设备制造商成功案例',
      shortTitle: "智能电表原始设备制造商",
      subtitle: '低功耗计量解决方案，延长设备生命周期',
      metric1: '低功耗SIM卡',
      metric2: '电池寿命',
      metric3: '成本降低',
      metric4: '80万张低功耗SIM卡 • 10年电池寿命',
      highlight: '成本降低50%',
      challengeText1: '某智能电表制造商需要超低功耗的连接解决方案，以支持远程公用事业计量部署的10年以上电池寿命。传统蜂窝网络连接功耗过高，且不适用于大规模电表部署的成本需求。',
      challengeText2: '该解决方案需要具备深度室内穿透能力、最低功耗消耗，以及适用于公用事业计量应用中常见的低频、小数据传输的经济高效数据套餐。',
      solution1Title: '低数据量连接服务',
      solution1Desc: '部署专为超低功耗优化的专用低数据量SIM卡，实现10年以上电池寿命，同时具备卓越的室内覆盖与穿透能力。',
      solution2Title: '优化数据套餐',
      solution2Desc: '针对智能电表通信常见的低频、小包数据传输，定制经济高效的数据套餐，将运营成本降低50%。',
      solution3Title: '自动配置服务',
      solution3Desc: '通过自动化配置API简化SIM卡激活与设备入驻流程，缩短部署时间并消除手动配置错误。',
      result1: '数万台电表成功部署，实现10年以上电池寿命',
      result2: '相比之前的连接解决方案，成本降低50%',
      result3: '即使在复杂室内环境中，读数成功率仍达99%',
      result4: '通过自动化配置API实现零接触部署',
      ctaTitle: '需要低功耗物联网连接服务？',
      ctaDesc: '了解低数据量SIM卡如何为您的公用事业或智慧城市部署提供支持',
    },
    GPS: {
      badge: '全球供应链可视化',
      title: '全球定位系统与多式联运追踪成功案例',
      shortTitle: "全球定位系统追踪",
      subtitle: '一带一路，全局可视',
      metric2: '覆盖国家',
      metric3: '平台运行时间',
      metric4: '新丝绸之路',
      highlight: '100%合规',
      challengeText1: '某领先电动汽车制造商需要可靠、可扩展的物联网连接解决方案，以支持其在欧洲和亚洲快速扩张的车队。其现有连接基础设施分散在多个运营商之间，导致覆盖缺口、性能不一致和计费复杂等问题。',
      challengeText2: '该公司需要在62个国家提供实时车辆追踪、诊断、远程在线更新和车队管理功能，并要求具备无缝漫游能力和运营商级可靠性。',
      solution1Title: '全球前50大移动网络运营商服务',
      solution1Desc: '部署单张SIM卡，支持在“一带一路”新丝绸之路沿线所有运营区域自动切换网络，实现最优覆盖与成本效益。',
      solution2Title: '工厂友好型物流服务',
      solution2Desc: '单张SIM卡可满足中国境内测试、一带一路铁路运输、欧洲售后服务等多场景使用需求。',
      solution3Title: '实时管理平台',
      solution3Desc: '提供全面的连接管理平台，具备实时诊断、用量分析和自动告警功能，支持主动问题解决。',
      result1: '所有市场均实现99%运行时间，超出服务等级协议要求',
      result2: '通过优化运营商选择，连接成本降低40%',
      result3: '中国原始设备制造商将35天的海运航程缩短为18天的铁路运输，且无需额外增加SIM卡',
      result4: '实时诊断功能支持预测性维护，减少停机时间',
      ctaTitle: '一带一路，全局可视',
      ctaDesc: '让我们探讨适合您业务场景的全球定位系统追踪物联网解决方案',
    },
    medical: {
      badge: '医疗健康行业',
      title: '医疗设备成功案例',
      shortTitle: "医疗设备",
      subtitle: '获得FDA与工信部认证的连接服务，支持全球医疗物联网部署',
      metric1: 'FDA认证',
      metric2: '工信部认证',
      metric3: '双市场覆盖',
      challengeText1: '某医疗设备制造商需要同时在美国和中国市场推出其联网患者监测系统。该挑战涉及应对复杂的监管要求，同时保障符合HIPAA标准的安全数据传输。',
      challengeText2: '两个市场不同的认证流程、网络要求和数据隐私法规，导致部署复杂度显著增加，并存在延期风险。',
      solution1Title: '监管合规套餐',
      solution1Desc: '提供端到端合规支持，包括美国FDA认证和中国工信部型号核准，涵盖技术文档编制、网络合规证明和认证指导。',
      solution2Title: '符合HIPAA标准的连接服务',
      solution2Desc: '部署私有APN并采用加密连接，满足HIPAA对受保护健康信息（PHI）的要求，确保两个市场的患者数据安全。',
      solution3Title: '双市场SIM解决方案',
      solution3Desc: '部署通过双市场认证的统一eUICC SIM卡，无需单独库存管理，简化供应链流程。',
      result1: '6个月内完成FDA认证与工信部型号核准',
      result2: '实现美国和中国市场同步上市',
      result3: '100%符合HIPAA标准，无数据泄露事件',
      result4: '相比竞争对手，上市时间缩短30%',
      ctaTitle: '准备好推出您的医疗物联网设备？',
      ctaDesc: '让我们携手应对监管合规挑战，助力您的医疗健康物联网部署',
    },
    mobility: {
      badge: '交通运输行业',
      title: '共享出行平台成功案例',
      shortTitle: "共享出行",
      subtitle: '符合DLT标准的短信营销活动，提升印度市场用户参与度',
      metric1: '月发送短信量',
      metric2: 'DLT合规',
      metric3: '打开率',
      challengeText1: '某大型共享出行平台在印度市场面临短信营销活动发送难题，原因是印度电信管理局（TRAI）推出的复杂分布式账本技术（DLT）法规。其营销短信被拦截，导致用户参与度和预订量大幅下降。',
      challengeText2: '该平台需要快速完成DLT注册、模板审批和发送者ID白名单申请，覆盖多个电信运营商，以恢复其营销能力。',
      solution1Title: '完整DLT入驻服务',
      solution1Desc: '提供端到端DLT注册服务，包括主体入驻、模板创建与审批、发送者ID注册和运营商白名单申请。',
      solution2Title: '模板优化服务',
      solution2Desc: '优化短信模板以提高审批通过率，同时保持营销效果，建立预审批模板库支持快速营销活动部署。',
      solution3Title: '多运营商整合',
      solution3Desc: '与印度所有主要电信运营商整合，确保稳定的发送成功率和全面的用户覆盖。',
      result1: '每月发送500万条以上合规短信',
      result2: '100%符合DLT标准，无短信拦截情况',
      result3: '短信打开率提升40%',
      result4: '新营销模板DLT设置仅需48小时',
      ctaTitle: '需要在印度开展DLT合规短信营销？',
      ctaDesc: '让我们助力您的营销活动全面开展',
    },
  },
};
